baseURL = "https://erick.navarro.io"
title = "Erick Navarro"
theme = "hugo-theme-nostyleplease"

[markup]
  [markup.highlight]
    style = 'github-dark'

  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = false

[params]
  favicon = "https://www.gravatar.com/avatar/0c44573e5cbcd1b3d32c27e7d7b367da?size=32"

  [params.theme_config]
    appearance        = "auto"
    date_format       = "2006-01-02"
    isListGroupByDate = true
    isShowFooter      = true
    show_description  = true
