baseURL = "/"
languageCode = "en-us"
title = "Some code and thoughts"
theme = "beautifulhugo"
markup = "org"
pygmentsCodeFences = true
pygmentsUseClasses = true

[Params]
  rss = true
  comments = true
  readingTime = true

[Author]
  name = "Erick Navarro"
  email = "erick@navarro.io"
  twitter = "erickgnavar"
  github = "erickgnavar"
  gitlab = "erickgnavar"
  instagram = "erickgnavar"
  spotify = "erickgnavar"
  linkedin = "erickgnavar"
  telegram = "erickgnavar"
  paypal = "erickgnavar"
  website = "https://erick.navarro.io"

[[menu.main]]
  name = "Blog"
  url = "blog"
  title = "Blog"

[[menu.main]]
  name = "About me"
  url = "about"

[[menu.main]]
  name = "My dotfiles"
  url = "https://github.com/erickgnavar/dotfiles"

[[menu.main]]
  name = "Projects"
  url = "projects"
