baseURL = "/"
languageCode = "en-us"
title = "Some code and thoughts"
theme = "hugo-coder"
markup = "org"
pygmentsCodeFences = true

[params]
  rss = true
  author = "Erick Navarro"
  info = "Software Developer"
  description = "Erick Navarro's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "https://www.gravatar.com/avatar/0c44573e5cbcd1b3d32c27e7d7b367da?size=300"

  favicon_32 = "https://www.gravatar.com/avatar/0c44573e5cbcd1b3d32c27e7d7b367da?size=32"
  favicon_16 = "https://www.gravatar.com/avatar/0c44573e5cbcd1b3d32c27e7d7b367da?size=16"

  hidecredits = false
  hidecopyright = false

  rtl = false
  math = true

[[params.social]]
  name = "Twitter"
  icon = "fab fa-twitter fa-2x"
  weight = 1
  url = "https://twitter.com/erickgnavar/"

[[params.social]]
  name = "Github"
  icon = "fab fa-github fa-2x"
  weight = 2
  url = "https://github.com/erickgnavar/"

[[params.social]]
  name = "Gitlab"
  icon = "fab fa-gitlab fa-2x"
  weight = 3
  url = "https://gitlab.com/erickgnavar/"

[[params.social]]
  name = "Linkedin"
  icon = "fab fa-linkedin fa-2x"
  weight = 4
  url = "https://linkedin.com/in/erickgnavar/"

[[menu.main]]
  name = "Blog"
  url = "blog"
  title = "Blog"

[[menu.main]]
  name = "About me"
  url = "about"

[[menu.main]]
  name = "My dotfiles"
  url = "https://github.com/erickgnavar/dotfiles"

[[menu.main]]
  name = "Projects"
  url = "projects"
