---
title: "Projects"
date: 2018-12-23T22:29:26-05:00
---

* Emacs packages

** [[https://github.com/erickgnavar/linkode.el][linkode.el]]
Upload buffer or region to [[http://linkode.org][linkode.org]], a pastebin-like service.

** [[https://github.com/erickgnavar/tree-sitter-ispell.el][tree-sitter-ispell.el]]
[[https://tree-sitter.github.io/tree-sitter/][tree-sitter]] plugin to run ispell on text nodes across languages.

** [[https://github.com/erickgnavar/treesit-ispell.el][treesit-ispell.el]]
Same as above but using Emacs's native ~treesit~ package.

** [[https://github.com/erickgnavar/flymake-sqlfluff][flymake-sqlfluff]]
~flymake~ plugin for SQL linting via [[https://www.sqlfluff.com][sqlfluff]].

** [[https://github.com/erickgnavar/flymake-ruff][flymake-ruff]]
~flymake~ plugin for Python linting via [[https://pypi.org/project/ruff/][ruff]].

** [[https://github.com/erickgnavar/cloak-mode][cloak-mode]]
Minor mode to hide sensitive data using per-major-mode regex patterns.

* Python libraries

** [[https://pypi.org/project/serpost/][Serpost]]
Fetch parcel tracking data from Peru's postal service using a tracking number.

** [[https://pypi.org/project/jr_tools/][jr_tools]]
Upload and configure reports in Jasper Server via a YAML-based config file.

* Odoo modules

** [[https://apps.odoo.com/apps/modules/11.0/l10n_pe_import_rxh/][l10n_pe_import_rxh]]
Import Peruvian RxH XML invoices and convert them into Odoo supplier invoices.

** [[https://apps.odoo.com/apps/modules/11.0/tracking_serpost_purchase/][tracking_serpost_purchase]]
[[http://www.serpost.com.pe][Serpost]] tracking data integrated into purchase orders.

** [[https://apps.odoo.com/apps/modules/11.0/tracking_serpost_sale/][tracking_serpost_sale]]
[[http://www.serpost.com.pe][Serpost]] tracking data integrated into sale orders.

* Alfred workflows

** [[https://github.com/erickgnavar/coinstats-alfred-workflow][coinstats]]
Query cryptocurrency prices via the [[https://coinmarketcap.com][CoinMarketCap]] API from Alfred.

** [[https://github.com/erickgnavar/currency-exchange-alfred-workflow][currency-exchange]]
Convert between currencies using exchange rates from a [[https://free.currencyconverterapi.com][free API]].

* Web apps

** [[https://github.com/erickgnavar/proma][proma]]
Manage clients, projects, timesheets, and invoices in one place.

* macOS apps

** [[http://erickgnavar.github.io/dynowall/][dynowall]]
Cycle your desktop wallpaper automatically using [[https://unsplash.com][Unsplash]] images.
