name: Check templates

on: push

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: extractions/setup-just@v3
      - uses: astral-sh/setup-uv@v5
      - run: just check
